name: Run Gold Rates Script

on:
  schedule:
    - cron: '0 0,8,16 * * *'  # Runs at midnight, 8 AM, and 4 PM UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: windows-latest  # Use Windows environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify Python 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      run: python gold_rates.py  # Ensure the script name matches

